name: Docker Image CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    # - name: Build the Docker image
    #   run: make build

    - name: Set Current Date
      env:
        TZ: 'Europe/Rome'
      run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_ROBOT_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_PASSWORD }}

    - name: Build Latest auth
      uses: docker/build-push-action@v6
      with:
        context: .
        file: auth/Dockerfile
        platforms: linux/amd64, linux/arm64
        push: true
        tags: |
          quay.io/nicolabeghin/gphotos-sync:auth-latest

    - name: Build Latest gphotos-sync
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        push: true
        tags: |
          quay.io/nicolabeghin/gphotos-sync:latest
