name: Docker Image CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    # - name: Build the Docker image
    #   run: make build

    - name: Build Latest auth
      uses: docker/build-push-action@v6
      with:
        context: .
        file: auth/Dockerfile
        platforms: linux/amd64, linux/arm64
        push: false
        tags: |
          quay.io/nicolabeghin/gphotos-sync:auth-latest

    - name: Build Latest gphotos-sync
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        push: false
        tags: |
          quay.io/nicolabeghin/gphotos-sync:latest
